In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_excel("../data/raw/Telco_customer_churn.xlsx")

In [5]:
df.drop(columns=['CustomerID',
                            'Count',
                            'Country',
                            'State',
                            'Lat Long',
                            'Churn Label',
                            'Churn Score',
                            'Churn Reason'],
                   inplace=True)

In [6]:
list(df.columns)

['City',
 'Zip Code',
 'Latitude',
 'Longitude',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Tenure Months',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charges',
 'Total Charges',
 'Churn Value',
 'CLTV']

In [7]:
df['Total Charges'].dtype

dtype('O')

In [8]:
df[df['Total Charges'].isin([" ",""])]['Total Charges'].count()

np.int64(11)

In [9]:
df[df['Total Charges'].isin([" ",""])][['Tenure Months','Monthly Charges','Total Charges']]

      Tenure Months  Monthly Charges Total Charges
2234              0            52.55
2438              0            20.25
2568              0            80.85
2667              0            25.75
2856              0            56.05
4331              0            19.85
4687              0            25.35
5104              0            20.00
5719              0            19.70
6772              0            73.35
6840              0            61.90

In [10]:
df.loc[df['Total Charges'].isin([" ",""]),"Total Charges"]=np.nan

In [11]:
df['Total Charges'].isna().sum()

np.int64(11)

In [12]:
df['Total Charges'].dtype

dtype('O')

In [13]:
df['Total Charges']=pd.to_numeric(df['Total Charges'])

In [14]:
df.loc[
    df['Total Charges'].isna(),
['Tenure Months','Monthly Charges','Total Charges','Churn Value']]

      Tenure Months  Monthly Charges  Total Charges  Churn Value
2234              0            52.55            NaN            0
2438              0            20.25            NaN            0
2568              0            80.85            NaN            0
2667              0            25.75            NaN            0
2856              0            56.05            NaN            0
4331              0            19.85            NaN            0
4687              0            25.35            NaN            0
5104              0            20.00            NaN            0
5719              0            19.70            NaN            0
6772              0            73.35            NaN            0
6840              0            61.90            NaN            0

In [15]:
df.fillna({'Total Charges':0},inplace=True)

,City,Zip Code,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value,CLTV
0,Los Angeles,90003,33.964131,-118.272783,Male,No,No,No,2,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,3239
1,Los Angeles,90005,34.059281,-118.307420,Female,No,No,Yes,2,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,2701
2,Los Angeles,90006,34.048013,-118.293953,Female,No,No,Yes,8,Yes,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1,5372
3,Los Angeles,90010,34.062125,-118.315709,Female,No,Yes,Yes,28,Yes,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1,5003
4,Los Angeles,90015,34.039224,-118.266293,Male,No,No,Yes,49,Yes,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1,5340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Landers,92285,34.341737,-116.539416,Female,No,No,No,72,Yes,...,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.40,0,5306
7039,Adelanto,92301,34.667815,-117.536183,Male,No,Yes,Yes,24,Yes,...,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,0,2140
7040,Amboy,92304,34.559882,-115.637164,Female,No,Yes,Yes,72,Yes,...,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0,5560
7041,Angelus Oaks,92305,34.167800,-116.864330,Female,No,Yes,Yes,11,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,2793
7042,Apple Valley,92308,34.424926,-117.184503,Male,No,No,No,66,Yes,...,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0,5097

In [16]:
df['Total Charges'].isna().sum()

np.int64(0)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   str
 1   Zip Code           7043 non-null   int64
 2   Latitude           7043 non-null   float64
 3   Longitude          7043 non-null   float64
 4   Gender             7043 non-null   str
 5   Senior Citizen     7043 non-null   str
 6   Partner            7043 non-null   str
 7   Dependents         7043 non-null   str
 8   Tenure Months      7043 non-null   int64
 9   Phone Service      7043 non-null   str
 10  Multiple Lines     7043 non-null   str
 11  Internet Service   7043 non-null   str
 12  Online Security    7043 non-null   str
 13  Online Backup      7043 non-null   str
 14  Device Protection  7043 non-null   str
 15  Tech Support       7043 non-null   str
 16  Streaming TV       7043 non-null   str
 17  Streaming Movies   7043 non-null   str
 18  Contract           7043 non-null   str
 19  Paperless Billing  7043 non-null   str
 20  Payment Method     7043 non-null   str
 21  Monthly Charges    7043 non-null   float64
 22  Total Charges      7043 non-null   float64
 23  Churn Value        7043 non-null   int64
 24  CLTV               7043 non-null   int64
dtypes: float64(4), int64(4), str(17)
memory usage: 1.3 MB